export const listaEquipos = [{
    id: 1,
    nombre: 'Qatar',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'A',
    bombo: 1,
    logo: 'logo-qa.png',
    imgcampeon: 'champ-qa.png'
  },
  {
    id: 2,
    nombre: 'Ecuador',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'A',
    bombo: 2,
    logo: 'logo-ec.png',
    imgcampeon: 'champ-ec.png'
  },
  {
    id: 3,
    nombre: 'Senegal',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'A',
    bombo: 3,
    logo: 'logo-sn.png',
    imgcampeon: 'champ-sn.png'
  },
  {
    id: 4,
    nombre: 'Países Bajos',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'A',
    bombo: 4,
    logo: 'logo-nd.png',
    imgcampeon: 'champ-nd.png'
  },
  {
    id: 5,
    nombre: 'Inglaterra',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'B',
    bombo: 1,
    logo: 'logo-en.png',
    imgcampeon: 'champ-en.png'
  },
  {
    id: 6,
    nombre: 'Irán',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'B',
    bombo: 2,
    logo: 'logo-ir.png',
    imgcampeon: 'champ-ir.png'
  },
  {
    id: 7,
    nombre: 'Estados Unidos',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'B',
    bombo: 3,
    logo: 'logo-us.png',
    imgcampeon: 'champ-us.png'
  },
  {
    id: 8,
    nombre: 'Gales',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'B',
    bombo: 4,
    logo: 'logo-wa.png',
    imgcampeon: 'champ-wa.png'
  },
  {
    id: 9,
    nombre: 'Argentina',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'C',
    bombo: 1,
    logo: 'logo-ar.png',
    imgcampeon: 'champ-ar.png'
  },
  {
    id: 10,
    nombre: 'Arabia Saudita',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'C',
    bombo: 2,
    logo: 'logo-sa.png',
    imgcampeon: 'champ-sa.png'
  },
  {
    id: 11,
    nombre: 'México',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'C',
    bombo: 3,
    logo: 'logo-mx.png',
    imgcampeon: 'champ-mx.png'
  },
  {
    id: 12,
    nombre: 'Polonia',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'C',
    bombo: 4,
    logo: 'logo-pl.png',
    imgcampeon: 'champ-pl.png'
  },
  {
    id: 13,
    nombre: 'Francia',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'D',
    bombo: 1,
    logo: 'logo-fr.png',
    imgcampeon: 'champ-fr.png'
  },
  {
    id: 14,
    nombre: 'Australia',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'D',
    bombo: 2,
    logo: 'logo-au.png',
    imgcampeon: 'champ-au.png'
  },
  {
    id: 15,
    nombre: 'Dinamarca',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'D',
    bombo: 3,
    logo: 'logo-dk.png',
    imgcampeon: 'champ-dk.png'
  },
  {
    id: 16,
    nombre: 'Túnez',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'D',
    bombo: 4,
    logo: 'logo-tn.png',
    imgcampeon: 'champ-tn.png'
  },
  {
    id: 17,
    nombre: 'España',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'E',
    bombo: 1,
    logo: 'logo-es.png',
    imgcampeon: 'champ-es.png'
  },
  {
    id: 18,
    nombre: 'Costa Rica',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'E',
    bombo: 2,
    logo: 'logo-cr.png',
    imgcampeon: 'champ-cr.png'
  },
  {
    id: 19,
    nombre: 'Alemania',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'E',
    bombo: 3,
    logo: 'logo-de.png',
    imgcampeon: 'champ-de.png'
  },
  {
    id: 20,
    nombre: 'Japón',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'E',
    bombo: 4,
    logo: 'logo-jp.png',
    imgcampeon: 'champ-jp.png'
  },
  {
    id: 21,
    nombre: 'Bélgica',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'F',
    bombo: 1,
    logo: 'logo-be.png',
    imgcampeon: 'champ-be.png'
  },
  {
    id: 22,
    nombre: 'Canadá',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'F',
    bombo: 2,
    logo: 'logo-ca.png',
    imgcampeon: 'champ-ca.png'
  },
  {
    id: 23,
    nombre: 'Marruecos',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'F',
    bombo: 3,
    logo: 'logo-ma.png',
    imgcampeon: 'champ-ma.png'
  },
  {
    id: 24,
    nombre: 'Croacia',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'F',
    bombo: 4,
    logo: 'logo-hr.png',
    imgcampeon: 'champ-hr.png'
  },
  {
    id: 25,
    nombre: 'Brasil',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'G',
    bombo: 1,
    logo: 'logo-br.png',
    imgcampeon: 'champ-br.png'
  },
  {
    id: 26,
    nombre: 'Serbia',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'G',
    bombo: 2,
    logo: 'logo-rs.png',
    imgcampeon: 'champ-rs.png'
  },
  {
    id: 27,
    nombre: 'Suiza',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'G',
    bombo: 3,
    logo: 'logo-ch.png',
    imgcampeon: 'champ-ch.png'
  },
  {
    id: 28,
    nombre: 'Camerún',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'G',
    bombo: 4,
    logo: 'logo-cm.png',
    imgcampeon: 'champ-cm.png'
  },
  {
    id: 29,
    nombre: 'Portugal',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 1,
    clasificado: 'faseDeGrupos',
    grupo: 'H',
    bombo: 1,
    logo: 'logo-pt.png',
    imgcampeon: 'champ-pt.png'
  },
  {
    id: 30,
    nombre: 'Ghana',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 2,
    clasificado: 'faseDeGrupos',
    grupo: 'H',
    bombo: 2,
    logo: 'logo-gh.png',
    imgcampeon: 'champ-gh.png'
  },
  {
    id: 31,
    nombre: 'Uruguay',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 3,
    clasificado: 'faseDeGrupos',
    grupo: 'H',
    bombo: 3,
    logo: 'logo-uy.png',
    imgcampeon: 'champ-uy.png'
  },
  {
    id: 32,
    nombre: 'Corea del Sur',
    puntos: 0,
    partidos: 0,
    victorias: 0,
    empates: 0,
    derrotas: 0,
    golesFavor: 0,
    golesContra: 0,
    puesto: 4,
    clasificado: 'faseDeGrupos',
    grupo: 'H',
    bombo: 4,
    logo: 'logo-kr.png',
    imgcampeon: 'champ-kr.png'
  }
];

export const listaPartidos = [{
    id: 1,
    grupo: 'A',
    fecha: 1,
    local: { nombre: 'Qatar', resultado: 1 },
    visitante: { nombre: 'Ecuador', resultado: 2 }
  },
  {
    id: 2,
    grupo: 'A',
    fecha: 1,
    local: { nombre: 'Senegal', resultado: 1 },
    visitante: { nombre: 'Países Bajos', resultado: 2 }
  },
  {
    id: 3,
    grupo: 'A',
    fecha: 2,
    local: { nombre: 'Países Bajos', resultado: 2 },
    visitante: { nombre: 'Ecuador', resultado: 0 }
  },
  {
    id: 4,
    grupo: 'A',
    fecha: 2,
    local: { nombre: 'Qatar', resultado: 1 },
    visitante: { nombre: 'Senegal', resultado: 4 }
  },
  {
    id: 5,
    grupo: 'A',
    fecha: 3,
    local: { nombre: 'Países Bajos', resultado: 3 },
    visitante: { nombre: 'Qatar', resultado: 0 }
  },
  {
    id: 6,
    grupo: 'A',
    fecha: 3,
    local: { nombre: 'Ecuador', resultado: 1 },
    visitante: { nombre: 'Senegal', resultado: 1 }
  },
  {
    id: 7,
    grupo: 'B',
    fecha: 1,
    local: { nombre: 'Inglaterra', resultado: 3 },
    visitante: { nombre: 'Irán', resultado: 1 }
  },
  {
    id: 8,
    grupo: 'B',
    fecha: 1,
    local: { nombre: 'Estados Unidos', resultado: 2 },
    visitante: { nombre: 'Gales', resultado: 1 }
  },
  {
    id: 9,
    grupo: 'B',
    fecha: 2,
    local: { nombre: 'Gales', resultado: 2 },
    visitante: { nombre: 'Irán', resultado: 1 }
  },
  {
    id: 10,
    grupo: 'B',
    fecha: 2,
    local: { nombre: 'Inglaterra', resultado: 2 },
    visitante: { nombre: 'Estados Unidos', resultado: 2 }
  },
  {
    id: 11,
    grupo: 'B',
    fecha: 3,
    local: { nombre: 'Gales', resultado: 1 },
    visitante: { nombre: 'Inglaterra', resultado: 2 }
  },
  {
    id: 12,
    grupo: 'B',
    fecha: 3,
    local: { nombre: 'Irán', resultado: 0 },
    visitante: { nombre: 'Estados Unidos', resultado: 1 }
  },
  {
    id: 13,
    grupo: 'C',
    fecha: 1,
    local: { nombre: 'Argentina', resultado: 3 },
    visitante: { nombre: 'Arabia Saudita', resultado: 0 }
  },
  {
    id: 14,
    grupo: 'C',
    fecha: 1,
    local: { nombre: 'México', resultado: 0 },
    visitante: { nombre: 'Polonia', resultado: 1 }
  },
  {
    id: 15,
    grupo: 'C',
    fecha: 2,
    local: { nombre: 'Polonia', resultado: 1 },
    visitante: { nombre: 'Arabia Saudita', resultado: 0 }
  },
  {
    id: 16,
    grupo: 'C',
    fecha: 2,
    local: { nombre: 'Argentina', resultado: 2 },
    visitante: { nombre: 'México', resultado: 0 }
  },
  {
    id: 17,
    grupo: 'C',
    fecha: 3,
    local: { nombre: 'Polonia', resultado: 1 },
    visitante: { nombre: 'Argentina', resultado: 2 }
  },
  {
    id: 18,
    grupo: 'C',
    fecha: 3,
    local: { nombre: 'Arabia Saudita', resultado: 0 },
    visitante: { nombre: 'México', resultado: 0 }
  },
  {
    id: 19,
    grupo: 'D',
    fecha: 1,
    local: { nombre: 'Francia', resultado: 2 },
    visitante: { nombre: 'Australia', resultado: 1 }
  },
  {
    id: 20,
    grupo: 'D',
    fecha: 1,
    local: { nombre: 'Dinamarca', resultado: 3 },
    visitante: { nombre: 'Túnez', resultado: 0 }
  },
  {
    id: 21,
    grupo: 'D',
    fecha: 2,
    local: { nombre: 'Túnez', resultado: 1 },
    visitante: { nombre: 'Australia', resultado: 1 }
  },
  {
    id: 22,
    grupo: 'D',
    fecha: 2,
    local: { nombre: 'Francia', resultado: 0 },
    visitante: { nombre: 'Dinamarca', resultado: 1 }
  },
  {
    id: 23,
    grupo: 'D',
    fecha: 3,
    local: { nombre: 'Túnez', resultado: 0 },
    visitante: { nombre: 'Francia', resultado: 2 }
  },
  {
    id: 24,
    grupo: 'D',
    fecha: 3,
    local: { nombre: 'Australia', resultado: 1 },
    visitante: { nombre: 'Dinamarca', resultado: 1 }
  },
  {
    id: 25,
    grupo: 'E',
    fecha: 1,
    local: { nombre: 'España', resultado: 3 },
    visitante: { nombre: 'Costa Rica', resultado: 1 }
  },
  {
    id: 26,
    grupo: 'E',
    fecha: 1,
    local: { nombre: 'Alemania', resultado: 2 },
    visitante: { nombre: 'Japón', resultado: 2 }
  },
  {
    id: 27,
    grupo: 'E',
    fecha: 2,
    local: { nombre: 'Japón', resultado: 2 },
    visitante: { nombre: 'Costa Rica', resultado: 1 }
  },
  {
    id: 28,
    grupo: 'E',
    fecha: 2,
    local: { nombre: 'España', resultado: 1 },
    visitante: { nombre: 'Alemania', resultado: 1 }
  },
  {
    id: 29,
    grupo: 'E',
    fecha: 3,
    local: { nombre: 'Japón', resultado: 1 },
    visitante: { nombre: 'España', resultado: 2 }
  },
  {
    id: 30,
    grupo: 'E',
    fecha: 3,
    local: { nombre: 'Costa Rica', resultado: 0 },
    visitante: { nombre: 'Alemania', resultado: 2 }
  },
  {
    id: 31,
    grupo: 'F',
    fecha: 1,
    local: { nombre: 'Bélgica', resultado: 1 },
    visitante: { nombre: 'Canadá', resultado: 1 }
  },
  {
    id: 32,
    grupo: 'F',
    fecha: 1,
    local: { nombre: 'Marruecos', resultado: 1 },
    visitante: { nombre: 'Croacia', resultado: 2 }
  },
  {
    id: 33,
    grupo: 'F',
    fecha: 2,
    local: { nombre: 'Croacia', resultado: 2 },
    visitante: { nombre: 'Canadá', resultado: 1 }
  },
  {
    id: 34,
    grupo: 'F',
    fecha: 2,
    local: { nombre: 'Bélgica', resultado: 2 },
    visitante: { nombre: 'Marruecos', resultado: 0 }
  },
  {
    id: 35,
    grupo: 'F',
    fecha: 3,
    local: { nombre: 'Croacia', resultado: 1 },
    visitante: { nombre: 'Bélgica', resultado: 1 }
  },
  {
    id: 36,
    grupo: 'F',
    fecha: 3,
    local: { nombre: 'Canadá', resultado: 1 },
    visitante: { nombre: 'Marruecos', resultado: 0 }
  },
  {
    id: 37,
    grupo: 'G',
    fecha: 1,
    local: { nombre: 'Brasil', resultado: 3 },
    visitante: { nombre: 'Serbia', resultado: 1 }
  },
  {
    id: 38,
    grupo: 'G',
    fecha: 1,
    local: { nombre: 'Suiza', resultado: 1 },
    visitante: { nombre: 'Camerún', resultado: 1 }
  },
  {
    id: 39,
    grupo: 'G',
    fecha: 2,
    local: { nombre: 'Camerún', resultado: 2 },
    visitante: { nombre: 'Serbia', resultado: 1 }
  },
  {
    id: 40,
    grupo: 'G',
    fecha: 2,
    local: { nombre: 'Brasil', resultado: 1 },
    visitante: { nombre: 'Suiza', resultado: 0 }
  },
  {
    id: 41,
    grupo: 'G',
    fecha: 3,
    local: { nombre: 'Camerún', resultado: 0 },
    visitante: { nombre: 'Brasil', resultado: 2 }
  },
  {
    id: 42,
    grupo: 'G',
    fecha: 3,
    local: { nombre: 'Serbia', resultado: 1 },
    visitante: { nombre: 'Suiza', resultado: 1 }
  },
  {
    id: 43,
    grupo: 'H',
    fecha: 1,
    local: { nombre: 'Portugal', resultado: 2 },
    visitante: { nombre: 'Ghana', resultado: 2 }
  },
  {
    id: 44,
    grupo: 'H',
    fecha: 1,
    local: { nombre: 'Uruguay', resultado: 2 },
    visitante: { nombre: 'Corea del Sur', resultado: 1 }
  },
  {
    id: 45,
    grupo: 'H',
    fecha: 2,
    local: { nombre: 'Corea del Sur', resultado: 1 },
    visitante: { nombre: 'Ghana', resultado: 1 }
  },
  {
    id: 46,
    grupo: 'H',
    fecha: 2,
    local: { nombre: 'Portugal', resultado: 0 },
    visitante: { nombre: 'Uruguay', resultado: 1 }
  },
  {
    id: 47,
    grupo: 'H',
    fecha: 3,
    local: { nombre: 'Corea del Sur', resultado: 0 },
    visitante: { nombre: 'Portugal', resultado: 1 }
  },
  {
    id: 48,
    grupo: 'H',
    fecha: 3,
    local: { nombre: 'Ghana', resultado: 1 },
    visitante: { nombre: 'Uruguay', resultado: 2 }
  },
  {
    id: 49,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1A', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2B', nombre: null, resultado: null, penales: null }
  },
  {
    id: 50,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1C', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2D', nombre: null, resultado: null, penales: null }
  },
  {
    id: 51,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1E', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2F', nombre: null, resultado: null, penales: null }
  },
  {
    id: 52,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1G', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2H', nombre: null, resultado: null, penales: null }
  },
  {
    id: 53,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1B', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2A', nombre: null, resultado: null, penales: null }
  },
  {
    id: 54,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1D', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2C', nombre: null, resultado: null, penales: null }
  },
  {
    id: 55,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1F', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2E', nombre: null, resultado: null, penales: null }
  },
  {
    id: 56,
    grupo: 'octavosFinal',
    fecha: 4,
    local: { id: '1H', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: '2G', nombre: null, resultado: null, penales: null }
  },
  {
    id: 57,
    grupo: 'cuartosFinal',
    fecha: 5,
    local: { id: 'GP49', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'GP50', nombre: null, resultado: null, penales: null }
  },
  {
    id: 58,
    grupo: 'cuartosFinal',
    fecha: 5,
    local: { id: 'GP51', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'GP52', nombre: null, resultado: null, penales: null }
  },
  {
    id: 59,
    grupo: 'cuartosFinal',
    fecha: 5,
    local: { id: 'GP53', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'GP54', nombre: null, resultado: null, penales: null }
  },
  {
    id: 60,
    grupo: 'cuartosFinal',
    fecha: 5,
    local: { id: 'GP55', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'GP56', nombre: null, resultado: null, penales: null }
  },
  {
    id: 61,
    grupo: 'semifinal',
    fecha: 6,
    local: { id: 'GP57', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'GP58', nombre: null, resultado: null, penales: null }
  },
  {
    id: 62,
    grupo: 'semifinal',
    fecha: 6,
    local: { id: 'GP59', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'GP60', nombre: null, resultado: null, penales: null }
  },
  {
    id: 63,
    grupo: 'partidoTercerLugar',
    fecha: 7,
    local: { id: 'PP61', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'PP62', nombre: null, resultado: null, penales: null }
  },
  {
    id: 64,
    grupo: 'final',
    fecha: 7,
    local: { id: 'GP61', nombre: null, resultado: null, penales: null },
    ganador: null,
    perdedor: null,
    visitante: { id: 'GP62', nombre: null, resultado: null, penales: null }
  },
]
