const grupos = [{
        id: 'A',
        equipos: [{
                nombre: 'Qatar',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-qa.png',
            },
            {
                nombre: 'Ecuador',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-ec.png',
            },
            {
                nombre: 'Senegal',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-sn.png',
            },
            {
                nombre: 'Países Bajos',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-nd.png',
            }
        ]
    },
    {
        id: 'B',
        equipos: [{
                nombre: 'Inglaterra',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-en.png',
            },
            {
                nombre: 'Irán',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-ir.png',
            },
            {
                nombre: 'Estados Unidos',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-us.png',
            },
            {
                nombre: 'Gales',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-wa.png',
            }
        ]
    },
    {
        id: 'C',
        equipos: [{
                nombre: 'Argentina',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-ar.png',
            },
            {
                nombre: 'Arabia Saudita',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-sa.png',
            },
            {
                nombre: 'México',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-mx.png',
            },
            {
                nombre: 'Polonia',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-pl.png',
            }
        ]
    },
    {
        id: 'D',
        equipos: [{
                nombre: 'Francia',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-fr.png',
            },
            {
                nombre: 'Australia',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-au.png',
            },
            {
                nombre: 'Dinamarca',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-dk.png',
            },
            {
                nombre: 'Túnez',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-tn.png',
            }
        ]
    },
    {
        id: 'E',
        equipos: [{
                nombre: 'España',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-es.png',
            },
            {
                nombre: 'Costa Rica',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-cr.png',
            },
            {
                nombre: 'Alemania',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-de.png',
            },
            {
                nombre: 'Japón',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-jp.png',
            }
        ]
    },
    {
        id: 'F',
        equipos: [{
                nombre: 'Bélgica',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-be.png',
            },
            {
                nombre: 'Canadá',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-ca.png',
            },
            {
                nombre: 'Marruecos',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-ma.png',
            },
            {
                nombre: 'Croacia',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-hr.png',
            }
        ]
    },
    {
        id: 'G',
        equipos: [{
                nombre: 'Brasil',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-br.png',
            },
            {
                nombre: 'Serbia',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-rs.png',
            },
            {
                nombre: 'Suiza',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-ch.png',
            },
            {
                nombre: 'Camerún',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-cm.png',
            }
        ]
    },
    {
        id: 'H',
        equipos: [{
                nombre: 'Portugal',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 1,
                logo: 'logo-pt.png',
            },
            {
                nombre: 'Ghana',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 2,
                logo: 'logo-gh.png',
            },
            {
                nombre: 'Uruguay',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 3,
                logo: 'logo-uy.png',
            },
            {
                nombre: 'Corea del Sur',
                puntos: 0,
                partidos: 0,
                victorias: 0,
                empates: 0,
                derrotas: 0,
                golesFavor: 0,
                golesContra: 0,
                diferenciaGoles: 0,
                bombo: 4,
                logo: 'logo-kr.png',
            }
        ]
    }
];

export default grupos;