const listaEquipos = [{
        nombre: 'Qatar',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'A',
        bombo: 1,
        logo: 'logo-qa.png'
    },
    {
        nombre: 'Ecuador',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'A',
        bombo: 2,
        logo: 'logo-ec.png'
    },
    {
        nombre: 'Senegal',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'A',
        bombo: 3,
        logo: 'logo-sn.png'
    },
    {
        nombre: 'Países Bajos',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'A',
        bombo: 4,
        logo: 'logo-nd.png'
    },
    {

        nombre: 'Inglaterra',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'B',
        bombo: 1,
        logo: 'logo-en.png'
    },
    {
        nombre: 'Irán',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'B',
        bombo: 2,
        logo: 'logo-ir.png'
    },
    {
        nombre: 'Estados Unidos',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'B',
        bombo: 3,
        logo: 'logo-us.png'
    },
    {
        nombre: 'Gales',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'B',
        bombo: 4,
        logo: 'logo-wa.png'
    },
    {
        nombre: 'Argentina',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'C',
        bombo: 1,
        logo: 'logo-ar.png'
    },
    {
        nombre: 'Arabia Saudita',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'C',
        bombo: 2,
        logo: 'logo-sa.png'
    },
    {
        nombre: 'México',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'C',
        bombo: 3,
        logo: 'logo-mx.png'
    },
    {
        nombre: 'Polonia',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'C',
        bombo: 4,
        logo: 'logo-pl.png'
    },
    {
        nombre: 'Francia',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'D',
        bombo: 1,
        logo: 'logo-fr.png'
    },
    {
        nombre: 'Australia',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'D',
        bombo: 2,
        logo: 'logo-au.png'
    },
    {
        nombre: 'Dinamarca',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'D',
        bombo: 3,
        logo: 'logo-dk.png'
    },
    {
        nombre: 'Túnez',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'D',
        bombo: 4,
        logo: 'logo-tn.png'
    },
    {
        nombre: 'España',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'E',
        bombo: 1,
        logo: 'logo-es.png'
    },
    {
        nombre: 'Costa Rica',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'E',
        bombo: 2,
        logo: 'logo-cr.png'
    },
    {
        nombre: 'Alemania',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'E',
        bombo: 3,
        logo: 'logo-de.png'
    },
    {
        nombre: 'Japón',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'E',
        bombo: 4,
        logo: 'logo-jp.png'
    },
    {
        nombre: 'Bélgica',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'F',
        bombo: 1,
        logo: 'logo-be.png'
    },
    {
        nombre: 'Canadá',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'F',
        bombo: 2,
        logo: 'logo-ca.png'
    },
    {
        nombre: 'Marruecos',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'F',
        bombo: 3,
        logo: 'logo-ma.png'
    },
    {
        nombre: 'Croacia',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'F',
        bombo: 4,
        logo: 'logo-hr.png'
    },
    {
        nombre: 'Brasil',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'G',
        bombo: 1,
        logo: 'logo-br.png'
    },
    {
        nombre: 'Serbia',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'G',
        bombo: 2,
        logo: 'logo-rs.png',
    },
    {
        nombre: 'Suiza',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'G',
        bombo: 3,
        logo: 'logo-ch.png'
    },
    {
        nombre: 'Camerún',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'G',
        bombo: 4,
        logo: 'logo-cm.png'
    },
    {
        nombre: 'Portugal',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'H',
        bombo: 1,
        logo: 'logo-pt.png'
    },
    {
        nombre: 'Ghana',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'H',
        bombo: 2,
        logo: 'logo-gh.png'
    },
    {
        nombre: 'Uruguay',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'H',
        bombo: 3,
        logo: 'logo-uy.png'
    },
    {
        nombre: 'Corea del Sur',
        puntos: 0,
        partidos: 0,
        victorias: 0,
        empates: 0,
        derrotas: 0,
        golesFavor: 0,
        golesContra: 0,
        grupo: 'H',
        bombo: 4,
        logo: 'logo-kr.png',
    }
];

let listaPartidos = [];

for (let grupo of['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']) {
    let [equipo1, equipo2, equipo3, equipo4] = listaEquipos.filter(equipo => equipo.grupo === grupo);
    const partidos = [
        { id: 1, fecha: 1, local: { nombre: equipo1.nombre, resultado: null }, visitante: { nombre: equipo2.nombre, resultado: null } },
        { id: 2, fecha: 1, local: { nombre: equipo3.nombre, resultado: null }, visitante: { nombre: equipo4.nombre, resultado: null } },
        { id: 3, fecha: 2, local: { nombre: equipo4.nombre, resultado: null }, visitante: { nombre: equipo2.nombre, resultado: null } },
        { id: 4, fecha: 2, local: { nombre: equipo1.nombre, resultado: null }, visitante: { nombre: equipo3.nombre, resultado: null } },
        { id: 5, fecha: 3, local: { nombre: equipo4.nombre, resultado: null }, visitante: { nombre: equipo1.nombre, resultado: null } },
        { id: 6, fecha: 3, local: { nombre: equipo2.nombre, resultado: null }, visitante: { nombre: equipo3.nombre, resultado: null } }
    ]
    listaPartidos.push(...partidos)
};

console.log(listaPartidos)